title: Anjali Dhabaria # your name (or website title) here
logo: "/images/20201005_142002.jpg?raw=true" # your photo (or logo) here

<br> <br>

description: 
  <a href="https://www.linkedin.com/in/anjali-dhabaria/">LinkedIn Page</a> <br> <br>
  <a href="/pdf/Resume_Anjali_Dhabaria.pdf">Resume</a> <br> <br>
  <a href="adhabaria3@gatech.edu">Email</a> <br> <br>
  <a href="https://github.com/anjalidhabaria">Github</a> <br> <br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
