title: Anjali Dhabaria # your name (or website title) here
logo: "/images/20201005_142002.jpg?raw=true" # your photo (or logo) here
description: 
  <a href="https://www.linkedin.com/in/anjali-dhabaria/">View My LinkedIn Page</a> 
  <a href="/pdf/Resume_Anjali_Dhabaria.pdf">Resume</a> 
  <a href="adhabaria3@gatech.edu">Email</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
